;;; -*- lexical-binding: t; -*-

;; Clean the slate.
(menu-bar-mode 0)
(tool-bar-mode 0)
(scroll-bar-mode 0)
(column-number-mode 1)

(setq tab-bar-show 1)
(tab-bar-mode 1)

(setq ring-bell-function 'ignore
      inhibit-startup-screen t
      use-short-answers t)

;; Base modifications.
(set-face-attribute 'default nil :height 140)

(which-key-mode 1)

(setq display-line-numbers-type 'relative)
(add-hook 'prog-mode-hook #'display-line-numbers-mode)
(add-hook 'text-mode-hook #'display-line-numbers-mode)
(add-hook 'conf-mode-hook #'display-line-numbers-mode)

(use-package indent-bars
  :hook ((prog-mode text-mode conf-mode) . indent-bars-mode)
  :custom
  (indent-bars-pattern "╎")
  (indent-bars-width-frac 0.25)
  (indent-bars-pad-frac 0.25)
  (indent-bars-zigzag nil)
  (indent-bars-color-by-depth nil)
  (indent-bars-highlight-current-depth nil)
  (indent-bars-treesit-support t))

;; Apply the theme generated by matugen.
(add-to-list 'custom-theme-load-path "~/.cache/emacs/themes/")
(load-theme 'dankcolors t)

;; Tree-sitter major mode mapping.
(setq treesit-font-lock-level 4)

(setq major-mode-remap-alist
      '((c-mode          . c-ts-mode)
        (c++-mode        . c++-ts-mode)
        (c-or-c++-mode   . c-or-c++-ts-mode)
        (conf-toml-mode  . toml-ts-mode)
        (css-mode        . css-ts-mode)
        (html-mode       . html-ts-mode)
        (java-mode       . java-ts-mode)
        (javascript-mode . js-ts-mode)
        (js-json-mode    . json-ts-mode)
        (js-mode         . js-ts-mode)
        (lua-mode        . lua-ts-mode)
        (mhtml-mode      . mhtml-ts-mode)
        (python-mode     . python-ts-mode)
        (sh-mode         . bash-ts-mode)))

(setq auto-mode-alist
      (append '(
                ("\\.astro\\'"                       . astro-ts-mode)
                ("\\.fish\\'"                        . fish-mode)
                ("\\.\\(?:hs\\|hs-boot\\|hsig\\)\\'" . haskell-mode)
                ("\\.kdl\\'"                         . kdl-mode)
                ("\\.lhs\\'"                         . haskell-literate-mode)
                ("\\.ml\\|\\.mli\\'"                 . ocaml-ts-mode)
                ("\\.nix\\'"                         . nix-ts-mode)
                ("\\.nu\\'"                          . nu-ts-mode)
                ("\\.scala\\|\\.sbt\\'"              . scala-ts-mode)
                ("\\.svelte\\'"                      . svelte-mode)
                ("\\.[tj]sx\\'"                      . tsx-ts-mode)
                ("\\.ts\\'"                          . typescript-ts-mode)
                ("\\.v\\'"                           . coq-mode)
               )
              auto-mode-alist))

;; Some other treesit config.
(add-to-list 'warning-suppress-types '(treesit-font-lock-rules-mismatch))

;; Minibuffer completions.
(use-package vertico
  :init
  (vertico-mode 1)
  :custom
  (vertico-cycle t))

;; Fuzzy matching.
(use-package orderless
  :custom
  (completion-styles '(orderless basic))
  (completion-category-defaults nil)
  (completion-category-overrides '((file (styles partial-completion)))))

;; Buffer navigation.
(use-package consult
  :custom
  (consult-async-min-input 1)
  (consult-async-input-throttle 0.1))

;; In-buffer code completion.
(use-package corfu
  :init
  (global-corfu-mode 1)
  :bind (:map corfu-map
              ("RET" . corfu-insert)
              ("<tab>" . corfu-next)
              ("<backtab>" . corfu-previous))
  :custom
  (corfu-auto t)
  (corfu-auto-delay 0.1)
  (corfu-auto-prefix 2)
  (corfu-cycle t)
  (corfu-preselect 'prompt))

(use-package cape
  :init
  (add-to-list 'completion-at-point-functions #'cape-file))

;; Jump and jump!
(use-package avy
  :custom
  (avy-timeout-seconds 0.3))

;; A nice terminal.
(use-package eat
  :init
  (setq eat-shell (or (executable-find "fish") "/usr/bin/env fish"))
  :custom
  (eat-kill-buffer-on-exit t))

;; Direnv support.
(use-package envrc
  :hook (after-init . envrc-global-mode))

;; Eglot, diagnostics and friends.
(setq-default indent-tabs-mode nil
              tab-width 2
              standard-indent 2
              c-basic-offset 2
              c-ts-mode-indent-offset 2
              java-ts-mode-indent-offset 2
              js-indent-level 2
              typescript-ts-mode-indent-offset 2
              css-indent-offset 2
              rust-ts-mode-indent-offset 2
              go-ts-mode-indent-offset 2
              yaml-indent-offset 2
              nix-ts-mode-indent-offset 2
              lua-ts-mode-indent-offset 2
              cmake-ts-mode-indent-offset 2
              dockerfile-ts-mode-indent-offset 2
              sh-basic-offset 2
              scala-indent:step 2
              haskell-indentation-layout-offset 2
              haskell-indentation-starter-offset 2
              haskell-indentation-left-offset 2)

(defun my/eglot-format-buffer-on-save ()
  (with-timeout (1.5 nil)
    (ignore-errors (eglot-format-buffer))))

(defun my/eglot-setup-managed-hooks ()
  (add-hook 'before-save-hook #'my/eglot-format-buffer-on-save nil t))

(use-package eglot
  :hook ((prog-mode . eglot-ensure)
         (eglot-managed-mode . my/eglot-setup-managed-hooks))
  :custom
  (eglot-sync-connect nil)
  :config
  (add-to-list 'eglot-server-programs '(astro-ts-mode                 . ("astro-ls" "--stdio")))
  (add-to-list 'eglot-server-programs '(coq-mode                      . ("coq-lsp")))
  (add-to-list 'eglot-server-programs '((elixir-ts-mode heex-ts-mode) . ("expert")))
  (add-to-list 'eglot-server-programs '(fish-mode                     . ("fish-lsp" "start" "--stdio")))
  (add-to-list 'eglot-server-programs '(nix-ts-mode                   . ("nixd")))
  (add-to-list 'eglot-server-programs '(nu-ts-mode                    . ("nu" "--lsp")))
  (add-to-list 'eglot-server-programs '(python-ts-mode                . ("basedpyright-langserver" "--stdio")))
  (add-to-list 'eglot-server-programs '(scala-ts-mode                 . ("metals")))
  (add-to-list 'eglot-server-programs '(svelte-mode                . ("svelteserver" "--stdio"))))

(setq project-vc-extra-root-markers
      '("pom.xml" "build.gradle" "build.sbt" "mvnw" "gradlew"
        "dune-project" "_CoqProject"
        "Cargo.toml"
        "package.json" "deno.json"
        "Makefile" "CMakeLists.txt" "meson.build" "xmake.lua"
        "pyproject.toml" "requirements.txt"
        "flake.nix" "cabal.project" "stack.yaml"))

(setq flymake-inline-diagnostics 'fancy)

(custom-set-faces
 '(flymake-error ((t (:height 1.0 :weight bold))))
 '(flymake-warning ((t (:height 1.0 :weight bold))))
 '(flymake-note ((t (:height 1.0 :weight bold))))
 '(flymake-error-echo ((t (:height 1.0))))
 '(flymake-warning-echo ((t (:height 1.0)))))

;; Meow keybindings setup.
(defun meow-setup ()
  (setq meow-cheatsheet-layout meow-cheatsheet-layout-qwerty)

  (meow-motion-define-key
   '("j" . meow-next)
   '("k" . meow-prev)
   '("<escape>" . ignore))

  (meow-leader-define-key
   '("d" . xref-find-definitions)
   '("b" . xref-go-back)
   '("r" . xref-find-references)
   '("k" . eldoc-doc-buffer)
   '("a" . eglot-code-actions)
   '("e" . eglot-rename)
   '("=" . eglot-format)
   '("f" . consult-fd)
   '("p" . consult-ripgrep)
   '("s" . consult-buffer)
   '("x" . kill-current-buffer)
   '("g" . avy-goto-char-timer)
   '("t" . eat)
   '("1" . meow-digit-argument)
   '("2" . meow-digit-argument)
   '("3" . meow-digit-argument)
   '("4" . meow-digit-argument)
   '("5" . meow-digit-argument)
   '("6" . meow-digit-argument)
   '("7" . meow-digit-argument)
   '("8" . meow-digit-argument)
   '("9" . meow-digit-argument)
   '("0" . meow-digit-argument)
   '("/" . meow-keypad-describe-key)
   '("?" . meow-cheatsheet))

  (meow-normal-define-key
   '("0" . meow-expand-0)
   '("9" . meow-expand-9)
   '("8" . meow-expand-8)
   '("7" . meow-expand-7)
   '("6" . meow-expand-6)
   '("5" . meow-expand-5)
   '("4" . meow-expand-4)
   '("3" . meow-expand-3)
   '("2" . meow-expand-2)
   '("1" . meow-expand-1)
   '("-" . negative-argument)
   '(";" . meow-reverse)
   '("," . meow-inner-of-thing)
   '("." . meow-bounds-of-thing)
   '("[" . meow-beginning-of-thing)
   '("]" . meow-end-of-thing)
   '("a" . meow-append)
   '("A" . meow-open-below)
   '("b" . meow-back-word)
   '("B" . meow-back-symbol)
   '("c" . meow-change)
   '("d" . meow-delete)
   '("D" . meow-backward-delete)
   '("e" . meow-next-word)
   '("E" . meow-next-symbol)
   '("f" . meow-find)
   '("g" . meow-cancel-selection)
   '("G" . meow-grab)
   '("h" . meow-left)
   '("H" . meow-left-expand)
   '("i" . meow-insert)
   '("I" . meow-open-above)
   '("j" . meow-next)
   '("J" . meow-next-expand)
   '("k" . meow-prev)
   '("K" . meow-prev-expand)
   '("l" . meow-right)
   '("L" . meow-right-expand)
   '("m" . meow-join)
   '("n" . meow-search)
   '("o" . meow-block)
   '("O" . meow-to-block)
   '("p" . meow-yank)
   '("q" . meow-quit)
   '("Q" . meow-goto-line)
   '("r" . meow-replace)
   '("R" . meow-swap-grab)
   '("s" . meow-kill)
   '("t" . meow-till)
   '("u" . meow-undo)
   '("U" . meow-undo-in-selection)
   '("v" . meow-visit)
   '("w" . meow-mark-word)
   '("W" . meow-mark-symbol)
   '("x" . meow-line)
   '("X" . meow-goto-line)
   '("y" . meow-save)
   '("Y" . meow-sync-grab)
   '("z" . meow-pop-selection)
   '("'" . repeat)
   '("<escape>" . ignore)))

(use-package meow
  :config
  (meow-setup)
  (meow-global-mode 1))

;; Helix-style mode cursors (Block in Normal/Motion, Line in Insert).
(with-eval-after-load 'meow
  (setq meow-cursor-type-normal 'box
        meow-cursor-type-insert '(bar . 2)
        meow-cursor-type-motion 'box
        meow-cursor-type-keypad 'box))

;; Helix-style whitespace indicators.
(setq whitespace-style '(face trailing whitespace-missing tabs spaces space-mark tab-mark))
(setq whitespace-display-mappings
      '((space-mark 32 [183] [46])
        (tab-mark 9 [187 9] [92 9])))
